# Generated by Django 5.2.7 on 2025-10-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'фильмы', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.AddField(
            model_name='films',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
