# Generated by Django 5.2.7 on 2025-10-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvShow', '0005_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'машина', 'verbose_name_plural': 'машины'},
        ),
    ]
