# Generated by Django 5.2.7 on 2025-10-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='clothing',
            options={'verbose_name': 'одежду', 'verbose_name_plural': 'одежда'},
        ),
    ]
