# Generated by Django 5.2.7 on 2025-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book/', verbose_name='загрузите обложку книги')),
                ('title', models.CharField(max_length=100, verbose_name='напишите название фильма')),
                ('description', models.TextField(verbose_name='укажите описание к фильму')),
                ('quatity_page', models.PositiveBigIntegerField(verbose_name='количество страниц')),
                ('author', models.CharField(max_length=100, verbose_name='автор')),
                ('book_audio', models.URLField(blank=True, verbose_name='ссылка на аудиокнигу')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
