# Generated by Django 5.2.7 on 2025-10-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quatity_page',
            new_name='quantity_page',
        ),
    ]
