# Generated by Django 5.2.7 on 2025-10-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_quatity_page_book_quantity_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
    ]
